apiVersion: v1
kind: PersistentVolume
metadata:
  name: vprodb-pv
  labels:
    type: vprodb
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  hostPath:
    path: /mnt/data/mysql
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tomcat-pv
  labels:
    type: tomcat
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  hostPath:
    path: /usr/local/tomcat/webapps