apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vprodb
  namespace: default
spec:
  serviceName: vprodb
  replicas: 1
  selector:
    matchLabels:
      app: vprodb

  template:
    metadata:
      labels:
        app: vprodb
    spec:
      containers:
      - name: vprodb
        image: mysql:8.0.45
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: db-pass
        volumeMounts:
        - name: vpro-db-data
          mountPath: /var/lib/mysql

      initContainers:
      - name: busybox
        image: busybox:latest
        args: ["rm", "-rf", "/var/lib/mysql/lost+found"]
        volumeMounts:
        - name: vpro-db-data
          mountPath: /var/lib/mysql

  volumeClaimTemplates:
  - metadata:
      name: vpro-db-data
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi